angular
	.module("myApp.products")
	.service("productService", function(){
		this.getAll = function getAllProducts(){
			return [
				{id : 1, name : "Pen", cost : 5, units : 100, desc : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi animi est beatae, facilis ducimus atque incidunt. Quod qui iusto labore, voluptatem eveniet, quidem dolore illo voluptas corporis ut ab praesentium.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati delectus commodi ullam voluptas ipsum reiciendis nam qui sapiente, provident et nesciunt officiis asperiores vero laudantium perspiciatis rerum distinctio dolore aliquam.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil laborum aperiam quis, assumenda saepe corporis incidunt, iste ipsum quos. Voluptate excepturi doloremque dolorem earum delectus quae illum ut, ducimus rerum?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, repellat, nemo? At ipsum dicta, dolore qui deleniti non maiores modi nostrum aspernatur optio fugit eligendi eius magnam, quos quaerat voluptas."},
				{id : 2, name : "Hen", cost : 100, units : 20, desc : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi animi est beatae, facilis ducimus atque incidunt. Quod qui iusto labore, voluptatem eveniet, quidem dolore illo voluptas corporis ut ab praesentium.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati delectus commodi ullam voluptas ipsum reiciendis nam qui sapiente, provident et nesciunt officiis asperiores vero laudantium perspiciatis rerum distinctio dolore aliquam.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil laborum aperiam quis, assumenda saepe corporis incidunt, iste ipsum quos. Voluptate excepturi doloremque dolorem earum delectus quae illum ut, ducimus rerum?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, repellat, nemo? At ipsum dicta, dolore qui deleniti non maiores modi nostrum aspernatur optio fugit eligendi eius magnam, quos quaerat voluptas."},
				{id : 3, name : "Den", cost : 250, units : 10, desc : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi animi est beatae, facilis ducimus atque incidunt. Quod qui iusto labore, voluptatem eveniet, quidem dolore illo voluptas corporis ut ab praesentium.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati delectus commodi ullam voluptas ipsum reiciendis nam qui sapiente, provident et nesciunt officiis asperiores vero laudantium perspiciatis rerum distinctio dolore aliquam.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil laborum aperiam quis, assumenda saepe corporis incidunt, iste ipsum quos. Voluptate excepturi doloremque dolorem earum delectus quae illum ut, ducimus rerum?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, repellat, nemo? At ipsum dicta, dolore qui deleniti non maiores modi nostrum aspernatur optio fugit eligendi eius magnam, quos quaerat voluptas."},
				{id : 4, name : "Ten", cost : 10, units : 10, desc : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi animi est beatae, facilis ducimus atque incidunt. Quod qui iusto labore, voluptatem eveniet, quidem dolore illo voluptas corporis ut ab praesentium.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati delectus commodi ullam voluptas ipsum reiciendis nam qui sapiente, provident et nesciunt officiis asperiores vero laudantium perspiciatis rerum distinctio dolore aliquam.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil laborum aperiam quis, assumenda saepe corporis incidunt, iste ipsum quos. Voluptate excepturi doloremque dolorem earum delectus quae illum ut, ducimus rerum?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, repellat, nemo? At ipsum dicta, dolore qui deleniti non maiores modi nostrum aspernatur optio fugit eligendi eius magnam, quos quaerat voluptas."},
				{id : 5, name : "Zen", cost : 100000, units : 1, desc : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi animi est beatae, facilis ducimus atque incidunt. Quod qui iusto labore, voluptatem eveniet, quidem dolore illo voluptas corporis ut ab praesentium.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati delectus commodi ullam voluptas ipsum reiciendis nam qui sapiente, provident et nesciunt officiis asperiores vero laudantium perspiciatis rerum distinctio dolore aliquam.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil laborum aperiam quis, assumenda saepe corporis incidunt, iste ipsum quos. Voluptate excepturi doloremque dolorem earum delectus quae illum ut, ducimus rerum?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, repellat, nemo? At ipsum dicta, dolore qui deleniti non maiores modi nostrum aspernatur optio fugit eligendi eius magnam, quos quaerat voluptas."}
			]
		};
		this.getById = function(id){
			return this.getAll().filter(function(product){
				return product.id === id;
			})[0];
		};
	});
	